environment:
  ELM_VERSION: "0.19.0-bugfix2"
  matrix:
  - nodejs_version: "10.0"
  - nodejs_version: "8.0"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - npm install
  - npm install -g elm@%ELM_VERSION%

test_script:
  - npm test

build: off
